/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Components;

import data.Configuration;
import data.ComputerRemoteHandler;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.util.ArrayList;
import javax.swing.BoxLayout;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author root
 */
public class AllComputerPanel extends javax.swing.JPanel {

    /**
     * Creates new form AllComputerPanel
     */
    public AllComputerPanel() {
        initComponents();
        Dimension d = Configuration.getScreenDimension();
        int width = d.width - 100;
        int height = d.height - 100;
        AdjustSize();
        Layer1jPanel.setLayout(new FlowLayout(FlowLayout.LEFT, 5, 5));
        Layer2Panel.setLayout(new FlowLayout(FlowLayout.LEFT, 5, 5));
        Layer3Panel.setLayout(new FlowLayout(FlowLayout.LEFT, 5, 5));
        Layer4Panel.setLayout(new FlowLayout(FlowLayout.LEFT, 5, 5));
        Layer5Panel.setLayout(new FlowLayout(FlowLayout.LEFT, 5, 5));

        setVisible(true);
        show();
        SwingUtilities.updateComponentTreeUI(this);
    }

    public AllComputerPanel(ArrayList<String> clientPCs) {
        initComponents();
        show();
    }

    public void addRemoteItemPanel(ArrayList<ComputerRemoteHandler> client) {
        int index = 1;
        for (ComputerRemoteHandler handleAllComputerRemote : client) {
            addItemToPanel(handleAllComputerRemote.getRemoteDisplayPanel(), index);
            index++;
        }
    }

    public void addItemToPanel(JPanel item, int index) {
        switch (index) {
            case 1:
            case 2:
            case 3:
            case 4:
            case 5:
                addItemToPanelLayer1(item);

                break;
            case 6:
            case 7:
            case 8:
            case 9:
            case 10: {
                addItemToPanelLayer2(item);
            }
            break;
            case 11:
            case 12:
            case 13:
            case 14:
            case 15: {
                addItemToPanelLayer3(item);
            }
        }
        //revalidate();
        SwingUtilities.updateComponentTreeUI(this);
    }

    public void addItemToPanelLayer1(JPanel item) {
        Layer1jPanel.add(item);
        Layer1jPanel.show();
        System.out.println("Panel added");
    }

    public void addItemToPanelLayer2(JPanel item) {
        Layer2Panel.add(item);
        Layer2Panel.show();
        System.out.println("Panel added");
    }

    public void addItemToPanelLayer3(JPanel item) {
        Layer3Panel.add(item);
        Layer3Panel.show();
        System.out.println("Panel added");
    }

    public void addItemToPanelLayer4(JPanel item) {
        Layer4Panel.add(item);
        Layer4Panel.show();
        System.out.println("Panel added");
    }

    public void addItemToPanelLayer5(JPanel item) {
        Layer5Panel.add(item);
        Layer5Panel.show();
        System.out.println("Panel added");
    }

    public void addItemToPanelLayer6(JPanel item) {
        //Layer6Panel.add(item);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Layer1jPanel = new javax.swing.JPanel();
        Layer2Panel = new javax.swing.JPanel();
        Layer3Panel = new javax.swing.JPanel();
        Layer4Panel = new javax.swing.JPanel();
        Layer5Panel = new javax.swing.JPanel();

        setMaximumSize(new java.awt.Dimension(1300, 700));
        setMinimumSize(new java.awt.Dimension(1300, 700));
        setPreferredSize(new java.awt.Dimension(1300, 700));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        Layer1jPanel.setPreferredSize(new java.awt.Dimension(633, 170));
        Layer1jPanel.setLayout(new javax.swing.BoxLayout(Layer1jPanel, javax.swing.BoxLayout.LINE_AXIS));
        add(Layer1jPanel);

        Layer2Panel.setPreferredSize(new java.awt.Dimension(633, 170));
        Layer2Panel.setLayout(new javax.swing.BoxLayout(Layer2Panel, javax.swing.BoxLayout.LINE_AXIS));
        add(Layer2Panel);

        Layer3Panel.setPreferredSize(new java.awt.Dimension(633, 170));
        Layer3Panel.setLayout(new javax.swing.BoxLayout(Layer3Panel, javax.swing.BoxLayout.LINE_AXIS));
        add(Layer3Panel);

        Layer4Panel.setPreferredSize(new java.awt.Dimension(633, 170));
        Layer4Panel.setLayout(new javax.swing.BoxLayout(Layer4Panel, javax.swing.BoxLayout.LINE_AXIS));
        add(Layer4Panel);

        Layer5Panel.setPreferredSize(new java.awt.Dimension(633, 170));
        Layer5Panel.setLayout(new javax.swing.BoxLayout(Layer5Panel, javax.swing.BoxLayout.LINE_AXIS));
        add(Layer5Panel);
    }// </editor-fold>//GEN-END:initComponents

    void AdjustSize() {
        Dimension d = Configuration.getScreenDimension();
        setPreferredSize(new Dimension((d.width - 60), (d.height - 10)));

        Layer1jPanel.setPreferredSize(new Dimension((d.width - 60), (d.height - 10)));
        Layer2Panel.setPreferredSize(new Dimension((d.width - 60), (d.height - 10)));
        Layer3Panel.setPreferredSize(new Dimension((d.width - 60), (d.height - 10)));
        Layer4Panel.setPreferredSize(new Dimension((d.width - 60), (d.height - 10)));
        Layer5Panel.setPreferredSize(new Dimension((d.width - 60), (d.height - 10)));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Layer1jPanel;
    private javax.swing.JPanel Layer2Panel;
    private javax.swing.JPanel Layer3Panel;
    private javax.swing.JPanel Layer4Panel;
    private javax.swing.JPanel Layer5Panel;
    // End of variables declaration//GEN-END:variables
}
