/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Components;

import javax.swing.Icon;
import javax.swing.JLabel;

/**
 *
 * @author root
 */
public class NavigationItem extends javax.swing.JPanel {

    /**
     * Creates new form NavigationItem
     */
    public NavigationItem() {
        initComponents();
        setVisible(true);
        show();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NavItemIconLabel = new javax.swing.JLabel();
        NavItemNameLabel = new javax.swing.JLabel();

        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        setMaximumSize(new java.awt.Dimension(180, 45));
        setMinimumSize(new java.awt.Dimension(180, 45));
        setPreferredSize(new java.awt.Dimension(180, 45));

        NavItemIconLabel.setMaximumSize(new java.awt.Dimension(40, 40));
        NavItemIconLabel.setMinimumSize(new java.awt.Dimension(40, 40));
        NavItemIconLabel.setPreferredSize(new java.awt.Dimension(40, 40));

        NavItemNameLabel.setText("v");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(NavItemIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NavItemNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NavItemIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(NavItemNameLabel))
        );
    }// </editor-fold>//GEN-END:initComponents

    public Icon getNavItemIcon() {
        return NavItemIconLabel.getIcon();
    }

    public void setNavItemIconLabel(String navItemIconPath) {
        this.NavItemIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource(navItemIconPath)));
    }

    public String getNavItemNameLabel() {
        return NavItemNameLabel.getText();
    }

    public void setNavItemNameLabel(String navItemName) {
        this.NavItemNameLabel.setText(navItemName);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NavItemIconLabel;
    private javax.swing.JLabel NavItemNameLabel;
    // End of variables declaration//GEN-END:variables
}
