/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Components;

import data.Configuration;
import data.Setting;
import javax.swing.JFrame;

/**
 *
 * @author root
 */
public class SendMessageChoices extends javax.swing.JFrame implements Runnable {

    /**
     * Creates new form SendMessageChoices
     */
    private String MessageType = "None";

    public SendMessageChoices() {
        super("MessageType-Thread-Class");
        initComponents();
        OkMessageButton.setEnabled(false);
        MessageIconLabel.setIcon(Configuration.getImageIcon("messaging_larg.jpeg"));
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        //setVisible(true);

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        MessageIconLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        UniCastTypeMessageRadioButton = new javax.swing.JRadioButton();
        MultiCastTypeMessageRadioButton = new javax.swing.JRadioButton();
        BroadCastTypeMessageRadioButton = new javax.swing.JRadioButton();
        OkMessageButton = new javax.swing.JButton();
        CancelMessageButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Select Message Type");
        setMaximumSize(new java.awt.Dimension(500, 300));
        setMinimumSize(new java.awt.Dimension(500, 300));
        setName("Message Type"); // NOI18N
        setResizable(false);

        MessageIconLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MessageIconLabel.setMaximumSize(new java.awt.Dimension(80, 80));
        MessageIconLabel.setMinimumSize(new java.awt.Dimension(80, 80));
        MessageIconLabel.setPreferredSize(new java.awt.Dimension(80, 80));

        jLabel1.setText("Select Message Type :");

        buttonGroup1.add(UniCastTypeMessageRadioButton);
        UniCastTypeMessageRadioButton.setText("Unicast Message");
        UniCastTypeMessageRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UniCastTypeMessageRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(MultiCastTypeMessageRadioButton);
        MultiCastTypeMessageRadioButton.setText("MultiCast Message");
        MultiCastTypeMessageRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MultiCastTypeMessageRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(BroadCastTypeMessageRadioButton);
        BroadCastTypeMessageRadioButton.setText("BroadCast Message");
        BroadCastTypeMessageRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BroadCastTypeMessageRadioButtonActionPerformed(evt);
            }
        });

        OkMessageButton.setText("OK");
        OkMessageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkMessageButtonActionPerformed(evt);
            }
        });

        CancelMessageButton.setText("Cancel");
        CancelMessageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelMessageButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(MessageIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BroadCastTypeMessageRadioButton)
                    .addComponent(MultiCastTypeMessageRadioButton)
                    .addComponent(UniCastTypeMessageRadioButton)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CancelMessageButton)
                .addGap(18, 18, 18)
                .addComponent(OkMessageButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(MessageIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel1)))
                .addGap(24, 24, 24)
                .addComponent(UniCastTypeMessageRadioButton)
                .addGap(18, 18, 18)
                .addComponent(MultiCastTypeMessageRadioButton)
                .addGap(18, 18, 18)
                .addComponent(BroadCastTypeMessageRadioButton)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OkMessageButton)
                    .addComponent(CancelMessageButton))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OkMessageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkMessageButtonActionPerformed
        //adding action to the selected choices
        disposeFrame();
    }//GEN-LAST:event_OkMessageButtonActionPerformed

    private void CancelMessageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelMessageButtonActionPerformed
        // TODO add your handling code here:
        MessageType = "Cancel";
        disposeFrame();
    }//GEN-LAST:event_CancelMessageButtonActionPerformed

    private void UniCastTypeMessageRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UniCastTypeMessageRadioButtonActionPerformed
        // TODO add your handling code here:
        OkMessageButton.setEnabled(true);
        MessageType = Setting.UNICAST_MESSAGE_TYPE;
    }//GEN-LAST:event_UniCastTypeMessageRadioButtonActionPerformed

    private void MultiCastTypeMessageRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MultiCastTypeMessageRadioButtonActionPerformed
        // TODO add your handling code here:
        OkMessageButton.setEnabled(true);
        MessageType = Setting.MULTICAST_MESSAGE_TYPE;
    }//GEN-LAST:event_MultiCastTypeMessageRadioButtonActionPerformed

    private void BroadCastTypeMessageRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BroadCastTypeMessageRadioButtonActionPerformed
        // TODO add your handling code here:
        OkMessageButton.setEnabled(true);
        MessageType = Setting.BROADCAST_MESSAGE_TYPE;
    }//GEN-LAST:event_BroadCastTypeMessageRadioButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton BroadCastTypeMessageRadioButton;
    private javax.swing.JButton CancelMessageButton;
    private javax.swing.JLabel MessageIconLabel;
    private javax.swing.JRadioButton MultiCastTypeMessageRadioButton;
    private javax.swing.JButton OkMessageButton;
    private javax.swing.JRadioButton UniCastTypeMessageRadioButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    private void disposeFrame() {
        this.dispose();
    }

    public String getMessageType() {
        return MessageType;
    }

    @Override
    public void run() {

        show();
    }
}
