/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Client.ClientMessages;

import data.BroadCastClient;
import data.Configuration;
import java.awt.Dimension;
import java.io.IOException;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author root
 */
public class BroadCastMessageClient extends javax.swing.JFrame implements Runnable{

    /**
     * Creates new form BroadCastMessageClient
     */
    private BroadCastClient broadCastClient;
    public BroadCastMessageClient(String msg) {
        initComponents();
        setMaximumSize(new Dimension(400, 170));
        //setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        //setLocationRelativeTo(null);
        BroadCastIconLabel.setIcon(Configuration.getImageIcon("broadcast_ic.png"));
        BroadcastMessageLabel.setText(msg);
        //broadCastClient=new BroadCastClient();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BroadCastIconLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BroadcastMessageLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 238));
        setMinimumSize(new java.awt.Dimension(400, 238));
        setPreferredSize(new java.awt.Dimension(400, 238));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BroadCastIconLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BroadCastIconLabel.setMaximumSize(new java.awt.Dimension(40, 40));
        BroadCastIconLabel.setMinimumSize(new java.awt.Dimension(40, 40));
        BroadCastIconLabel.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(BroadCastIconLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setText("Broad Cast Message Recieved");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 12, -1, -1));
        getContentPane().add(BroadcastMessageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 45, 330, 38));

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 89, -1, -1));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 120, 32, -1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 120, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BroadCastIconLabel;
    private javax.swing.JLabel BroadcastMessageLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        //broadCastClient=new BroadCastClient(BroadCastIconLabel);
        //broadCastClient.start();
        //Thread.sleep(5000l);
        //boolean stop=broadCastClient.isMessageReceived();
        //while(!stop){
        //    stop=broadCastClient.isMessageReceived();
        //    System.out.println("Waiting for message");
        //}
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        show();
    }
}
