/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Client.ClientMessages;

import data.Configuration;
import java.io.IOException;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author root
 */
public class UnicastMessageClient extends javax.swing.JFrame implements Runnable {


    public UnicastMessageClient(String msg) {
        initComponents();
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        UnicastMessageLabel.setText(msg);
        jLabel1.setIcon(Configuration.getImageIcon("unicast_ic.png"));
        //show();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        UnicastMessageLabel = new javax.swing.JLabel();
        MessageOkButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel1.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel1.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setText("Unicast Message");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 12, 247, -1));
        getContentPane().add(UnicastMessageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 45, 357, 39));

        MessageOkButton.setText("OK");
        MessageOkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MessageOkButtonActionPerformed(evt);
            }
        });
        getContentPane().add(MessageOkButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 96, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MessageOkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MessageOkButtonActionPerformed
        try {
            dispose();
            //System.exit(1);
        } catch (Throwable ex) {
            Logger.getLogger(UnicastMessageClient.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_MessageOkButtonActionPerformed

    @Override
    public void run() {
        show();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MessageOkButton;
    private javax.swing.JLabel UnicastMessageLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
